weights: ''''''
cfg: E:\BUET Files\YOLOv5_Weight_Rewinding\models\yolov5n.yaml
data: custom_data.yaml
hyp: data\hyps\hyp.scratch-low.yaml
epochs: 1
batch_size: 40
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
save_initial_weights: false
rewind_weights: ''
save_dir: runs\train\exp
